// ============================================================================
// useAccounts — create BC weekly / monthly interest accounts
// ----------------------------------------------------------------------------
// Installments are auto-generated by DB triggers (see migration 003).
// ============================================================================
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/lib/supabase';
import { useAuth } from './useAuth';
import type { Account, AccountStatus, BcFrequency, AccountSource } from '@/types/database';

export function useAccounts(customerId?: string) {
  const { user } = useAuth();
  return useQuery({
    queryKey: ['accounts', customerId ?? 'all'],
    enabled: !!user,
    queryFn: async () => {
      let q = supabase.from('accounts').select('*').order('created_at', { ascending: false });
      if (customerId) q = q.eq('customer_id', customerId);
      const { data, error } = await q;
      if (error) throw error;
      return (data ?? []) as Account[];
    },
  });
}

interface BCInput {
  customer_id: string;
  amount_given: number;
  total_repayment_amount: number;
  term_weeks: number;
  bc_frequency: BcFrequency;
  start_date: string; // YYYY-MM-DD — this is treated as the first installment due date
  due_day?: string | null;
  notes?: string | null;
  source?: AccountSource;
}

interface MonthlyInput {
  customer_id: string;
  principal_amount: number;
  apr: number;
  start_date: string;
  due_day?: string | null; // day of month "1".."28"
  notes?: string | null;
}

export function useCreateBCAccount() {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async (input: BCInput) => {
      if (!user) throw new Error('Not authenticated');
      const { data, error } = await supabase
        .from('accounts')
        .insert({
          owner_user_id: user.id,
          account_type: 'BC_WEEKLY',
          ...input,
        })
        .select()
        .single();
      if (error) throw error;
      return data as Account;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['accounts'] });
      qc.invalidateQueries({ queryKey: ['installments'] });
      qc.invalidateQueries({ queryKey: ['dashboard'] });
    },
  });
}

interface AccountEditInput {
  id: string;
  status?: AccountStatus;
  start_date?: string;
  due_day?: string | null;
  notes?: string | null;
}

// Safe-field updates only. Amounts/term are intentionally excluded because
// installments + payments are derived from them at insert time.
export function useUpdateAccount() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({ id, ...patch }: AccountEditInput) => {
      const next: Record<string, unknown> = { ...patch };
      if (patch.status === 'CLOSED' || patch.status === 'DEFAULTED') {
        next.closed_at = new Date().toISOString();
      } else if (patch.status === 'ACTIVE') {
        next.closed_at = null;
      }
      const { data, error } = await supabase
        .from('accounts')
        .update(next)
        .eq('id', id)
        .select()
        .single();
      if (error) throw error;
      return data as Account;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['accounts'] });
      qc.invalidateQueries({ queryKey: ['installments'] });
      qc.invalidateQueries({ queryKey: ['dashboard'] });
      qc.invalidateQueries({ queryKey: ['dues'] });
    },
  });
}

export function useDeleteAccount() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (accountId: string) => {
      const { error } = await supabase.rpc('delete_account', { p_account_id: accountId });
      if (error) throw error;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['accounts'] });
      qc.invalidateQueries({ queryKey: ['installments'] });
      qc.invalidateQueries({ queryKey: ['dashboard'] });
      qc.invalidateQueries({ queryKey: ['dues'] });
    },
  });
}

export function useCreateMonthlyAccount() {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async (input: MonthlyInput) => {
      if (!user) throw new Error('Not authenticated');
      const { data, error } = await supabase
        .from('accounts')
        .insert({
          owner_user_id: user.id,
          account_type: 'MONTHLY_INTEREST',
          ...input,
        })
        .select()
        .single();
      if (error) throw error;
      return data as Account;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['accounts'] });
      qc.invalidateQueries({ queryKey: ['installments'] });
      qc.invalidateQueries({ queryKey: ['dashboard'] });
    },
  });
}
