// ============================================================================
// useAccounts — create BC weekly / monthly interest accounts
// ----------------------------------------------------------------------------
// Installments are auto-generated by DB triggers (see migration 003).
// ============================================================================
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/lib/supabase';
import { useAuth } from './useAuth';
import type { Account } from '@/types/database';

export function useAccounts(customerId?: string) {
  const { user } = useAuth();
  return useQuery({
    queryKey: ['accounts', customerId ?? 'all'],
    enabled: !!user,
    queryFn: async () => {
      let q = supabase.from('accounts').select('*').order('created_at', { ascending: false });
      if (customerId) q = q.eq('customer_id', customerId);
      const { data, error } = await q;
      if (error) throw error;
      return (data ?? []) as Account[];
    },
  });
}

interface BCInput {
  customer_id: string;
  amount_given: number;
  total_repayment_amount: number;
  term_weeks: number;
  start_date: string; // YYYY-MM-DD — this is treated as the first installment due date
  due_day?: string | null;
  notes?: string | null;
}

interface MonthlyInput {
  customer_id: string;
  principal_amount: number;
  apr: number;
  start_date: string;
  due_day?: string | null; // day of month "1".."28"
  notes?: string | null;
}

export function useCreateBCAccount() {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async (input: BCInput) => {
      if (!user) throw new Error('Not authenticated');
      const { data, error } = await supabase
        .from('accounts')
        .insert({
          owner_user_id: user.id,
          account_type: 'BC_WEEKLY',
          ...input,
        })
        .select()
        .single();
      if (error) throw error;
      return data as Account;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['accounts'] });
      qc.invalidateQueries({ queryKey: ['installments'] });
      qc.invalidateQueries({ queryKey: ['dashboard'] });
    },
  });
}

export function useCreateMonthlyAccount() {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async (input: MonthlyInput) => {
      if (!user) throw new Error('Not authenticated');
      const { data, error } = await supabase
        .from('accounts')
        .insert({
          owner_user_id: user.id,
          account_type: 'MONTHLY_INTEREST',
          ...input,
        })
        .select()
        .single();
      if (error) throw error;
      return data as Account;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['accounts'] });
      qc.invalidateQueries({ queryKey: ['installments'] });
      qc.invalidateQueries({ queryKey: ['dashboard'] });
    },
  });
}
