// ============================================================================
// MonthlyInterestForm — principal + APR account, monthly interest dues
// ----------------------------------------------------------------------------
// Monthly interest = principal × APR / 1200.
// First interest row generated by DB trigger; subsequent rows by the
// generate_monthly_interest_installments(account_id) callable function.
// ============================================================================
import { useMemo, useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Loader2 } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { Input, Textarea } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { useToast } from '@/components/ui/toast';
import { useCustomers } from '@/hooks/useCustomers';
import { useCreateMonthlyAccount } from '@/hooks/useAccounts';
import { useSettings } from '@/hooks/useSettings';
import { formatMoney, parseMoney } from '@/lib/currency';
import { todayISO } from '@/lib/utils';

interface Props {
  defaultCustomerId?: string;
  onCreated?: (id: string) => void;
}

export function MonthlyInterestForm({ defaultCustomerId, onCreated }: Props) {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const { toast } = useToast();
  const { data: customers } = useCustomers();
  const { data: settings } = useSettings();
  const create = useCreateMonthlyAccount();

  const [customerId, setCustomerId] = useState(defaultCustomerId ?? '');
  const [principal, setPrincipal] = useState('');
  const [apr, setApr] = useState<number>(settings?.default_apr ?? 24);
  const [startDate, setStartDate] = useState(todayISO());
  const [dueDay, setDueDay] = useState('1');
  const [notes, setNotes] = useState('');

  const principalNum = parseMoney(principal);
  const monthlyInterest = useMemo(() => {
    if (!principalNum || !apr) return 0;
    return Math.round(((principalNum * apr) / 1200) * 100) / 100;
  }, [principalNum, apr]);

  async function onSubmit(e: FormEvent) {
    e.preventDefault();
    if (!customerId) {
      toast(t('accounts.select_customer'), 'error');
      return;
    }
    if (principalNum <= 0) {
      toast('Enter a principal amount.', 'error');
      return;
    }
    try {
      const acct = await create.mutateAsync({
        customer_id: customerId,
        principal_amount: principalNum,
        apr,
        start_date: startDate,
        due_day: dueDay,
        notes: notes.trim() || null,
      });
      toast(t('accounts.created'), 'success');
      if (onCreated) onCreated(acct.id);
      else navigate(`/customers/${acct.customer_id}`);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Save failed';
      toast(msg, 'error');
    }
  }

  return (
    <form onSubmit={onSubmit} className="space-y-5">
      <div className="space-y-1.5">
        <Label>{t('accounts.customer')}</Label>
        <Select value={customerId} onValueChange={setCustomerId}>
          <SelectTrigger>
            <SelectValue placeholder={t('accounts.select_customer')} />
          </SelectTrigger>
          <SelectContent>
            {(customers ?? []).map((c) => (
              <SelectItem key={c.id} value={c.id}>
                {c.full_name} · {c.phone_number}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <div className="grid gap-4 sm:grid-cols-2">
        <div className="space-y-1.5">
          <Label htmlFor="principal">{t('accounts.principal')}</Label>
          <Input
            id="principal"
            inputMode="decimal"
            placeholder="100000"
            value={principal}
            onChange={(e) => setPrincipal(e.target.value)}
            className="tabular-money"
          />
        </div>
        <div className="space-y-1.5">
          <Label htmlFor="apr">{t('accounts.apr')}</Label>
          <Input
            id="apr"
            type="number"
            min={0}
            max={120}
            step="0.1"
            value={apr}
            onChange={(e) => setApr(Number(e.target.value) || 0)}
          />
        </div>
      </div>

      {/* Live computed monthly interest */}
      <div className="flex flex-wrap items-baseline justify-between gap-2 rounded-md border border-border/60 bg-accent/40 px-4 py-3">
        <span className="text-sm text-muted-foreground">{t('accounts.monthly_due_label')}</span>
        <span className="font-display text-lg font-semibold tabular-money text-primary">
          {formatMoney(monthlyInterest)}
        </span>
      </div>

      <div className="grid gap-4 sm:grid-cols-2">
        <div className="space-y-1.5">
          <Label htmlFor="start_date">{t('accounts.start_date')}</Label>
          <Input
            id="start_date"
            type="date"
            value={startDate}
            onChange={(e) => setStartDate(e.target.value)}
          />
        </div>
        <div className="space-y-1.5">
          <Label htmlFor="due_day">{t('accounts.monthly_due_day')}</Label>
          <Select value={dueDay} onValueChange={setDueDay}>
            <SelectTrigger id="due_day">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {Array.from({ length: 28 }, (_, i) => String(i + 1)).map((d) => (
                <SelectItem key={d} value={d}>
                  {d}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>

      <div className="space-y-1.5">
        <Label htmlFor="notes">{t('common.notes')}</Label>
        <Textarea
          id="notes"
          rows={2}
          value={notes}
          onChange={(e) => setNotes(e.target.value)}
        />
      </div>

      <div className="flex justify-end gap-2">
        <Button type="submit" size="lg" disabled={create.isPending}>
          {create.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
          {t('accounts.create')}
        </Button>
      </div>
    </form>
  );
}
