-- ============================================================================
-- Migration 001: Initial schema
-- ----------------------------------------------------------------------------
-- Run this first in Supabase → SQL Editor → New query → paste → Run.
-- Creates all tables, types, and indexes for the Lekka app.
-- ============================================================================

-- Enable required extensions
create extension if not exists "pgcrypto";

-- ----------------------------------------------------------------------------
-- Enums (using check constraints for portability instead of native enums)
-- ----------------------------------------------------------------------------
-- account_type:    BC_WEEKLY | MONTHLY_INTEREST
-- account_status:  ACTIVE | CLOSED | DEFAULTED
-- installment_st:  PENDING | PAID | PARTIAL | WAIVED
-- customer_status: ACTIVE | INACTIVE
-- payment_method:  CASH | UPI | PHONEPE | PAYTM | GPAY | BANK | OTHER
-- reminder_status: PENDING | SENT | CANCELLED
-- reminder_chan:   IN_APP | WHATSAPP | SMS

-- ----------------------------------------------------------------------------
-- customers
-- ----------------------------------------------------------------------------
create table public.customers (
  id              uuid primary key default gen_random_uuid(),
  owner_user_id   uuid not null references auth.users(id) on delete cascade,
  full_name       text not null,
  phone_number    text not null,
  address         text,
  notes           text,
  -- Telugu name for bilingual display, optional
  full_name_te    text,
  -- Optional photo URL (Supabase Storage bucket)
  photo_url       text,
  status          text not null default 'ACTIVE' check (status in ('ACTIVE','INACTIVE')),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index idx_customers_owner on public.customers(owner_user_id);
create index idx_customers_name  on public.customers(owner_user_id, lower(full_name));
create index idx_customers_phone on public.customers(owner_user_id, phone_number);
create index idx_customers_status on public.customers(owner_user_id, status);

-- ----------------------------------------------------------------------------
-- accounts
-- ----------------------------------------------------------------------------
-- One customer can have many accounts. Two flavors:
--   BC_WEEKLY: amount_given < total_repayment_amount, term_weeks set,
--              installments auto-generated on insert.
--   MONTHLY_INTEREST: principal_amount + apr set, monthly installments
--              generated by the function `generate_monthly_interest_installment`.
create table public.accounts (
  id                       uuid primary key default gen_random_uuid(),
  owner_user_id            uuid not null references auth.users(id) on delete cascade,
  customer_id              uuid not null references public.customers(id) on delete restrict,

  account_type             text not null check (account_type in ('BC_WEEKLY','MONTHLY_INTEREST')),
  status                   text not null default 'ACTIVE' check (status in ('ACTIVE','CLOSED','DEFAULTED')),

  -- BC_WEEKLY fields
  amount_given             numeric(14,2),
  total_repayment_amount   numeric(14,2),
  profit_amount            numeric(14,2) generated always as (
    coalesce(total_repayment_amount, 0) - coalesce(amount_given, 0)
  ) stored,
  term_weeks               int,

  -- MONTHLY_INTEREST fields
  principal_amount         numeric(14,2),
  apr                      numeric(6,3),  -- e.g. 24.000

  -- Common
  start_date               date not null,
  -- For BC: weekday name (MONDAY etc) OR null
  -- For monthly: day-of-month "1".."28"
  due_day                  text,
  notes                    text,

  closed_at                timestamptz,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),

  constraint bc_weekly_fields_valid check (
    account_type <> 'BC_WEEKLY' or (
      amount_given is not null and
      total_repayment_amount is not null and
      term_weeks is not null and term_weeks > 0
    )
  ),
  constraint monthly_fields_valid check (
    account_type <> 'MONTHLY_INTEREST' or (
      principal_amount is not null and apr is not null and apr >= 0
    )
  )
);

create index idx_accounts_owner    on public.accounts(owner_user_id);
create index idx_accounts_customer on public.accounts(customer_id);
create index idx_accounts_status   on public.accounts(owner_user_id, status);
create index idx_accounts_type     on public.accounts(owner_user_id, account_type);

-- ----------------------------------------------------------------------------
-- installments
-- ----------------------------------------------------------------------------
create table public.installments (
  id                  uuid primary key default gen_random_uuid(),
  owner_user_id       uuid not null references auth.users(id) on delete cascade,
  account_id          uuid not null references public.accounts(id) on delete cascade,

  installment_number  int not null,
  due_date            date not null,
  due_amount          numeric(14,2) not null,
  paid_amount         numeric(14,2) not null default 0,
  status              text not null default 'PENDING'
                      check (status in ('PENDING','PAID','PARTIAL','WAIVED')),
  paid_date           date,
  notes               text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  unique (account_id, installment_number)
);

create index idx_installments_owner     on public.installments(owner_user_id);
create index idx_installments_account   on public.installments(account_id);
create index idx_installments_due_date  on public.installments(owner_user_id, due_date);
create index idx_installments_status    on public.installments(owner_user_id, status);
-- Composite for "due today / overdue" queries
create index idx_installments_open      on public.installments(owner_user_id, due_date, status)
  where status in ('PENDING','PARTIAL');

-- ----------------------------------------------------------------------------
-- payments
-- ----------------------------------------------------------------------------
create table public.payments (
  id                uuid primary key default gen_random_uuid(),
  owner_user_id     uuid not null references auth.users(id) on delete cascade,
  account_id        uuid not null references public.accounts(id) on delete restrict,
  installment_id    uuid references public.installments(id) on delete set null,
  customer_id       uuid not null references public.customers(id) on delete restrict,

  amount            numeric(14,2) not null check (amount > 0),
  payment_date      date not null default current_date,
  payment_method    text not null default 'CASH'
                    check (payment_method in ('CASH','UPI','PHONEPE','PAYTM','GPAY','BANK','OTHER')),
  reference_number  text,
  confirmed_by      text,
  notes             text,

  -- Soft delete; never actually delete payment rows for audit trail.
  voided            boolean not null default false,
  voided_at         timestamptz,
  voided_reason     text,

  created_at        timestamptz not null default now()
);

create index idx_payments_owner     on public.payments(owner_user_id);
create index idx_payments_account   on public.payments(account_id);
create index idx_payments_customer  on public.payments(customer_id);
create index idx_payments_date      on public.payments(owner_user_id, payment_date);
create index idx_payments_inst      on public.payments(installment_id);

-- ----------------------------------------------------------------------------
-- reminders
-- ----------------------------------------------------------------------------
create table public.reminders (
  id              uuid primary key default gen_random_uuid(),
  owner_user_id   uuid not null references auth.users(id) on delete cascade,
  customer_id     uuid not null references public.customers(id) on delete cascade,
  account_id      uuid references public.accounts(id) on delete cascade,
  installment_id  uuid references public.installments(id) on delete cascade,

  reminder_type   text,  -- 'DUE_TODAY' | 'OVERDUE' | 'UPCOMING' | 'CUSTOM'
  scheduled_date  date,
  status          text not null default 'PENDING'
                  check (status in ('PENDING','SENT','CANCELLED')),
  channel         text not null default 'IN_APP'
                  check (channel in ('IN_APP','WHATSAPP','SMS')),
  message         text,
  sent_at         timestamptz,

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index idx_reminders_owner   on public.reminders(owner_user_id);
create index idx_reminders_status  on public.reminders(owner_user_id, status);
create index idx_reminders_date    on public.reminders(owner_user_id, scheduled_date);

-- ----------------------------------------------------------------------------
-- audit_logs
-- ----------------------------------------------------------------------------
create table public.audit_logs (
  id            uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  entity_type   text not null,        -- 'customer' | 'account' | 'installment' | 'payment'
  entity_id     uuid,
  action        text not null,        -- 'create' | 'update' | 'void' | 'close'
  old_value     jsonb,
  new_value     jsonb,
  created_by    uuid references auth.users(id),
  created_at    timestamptz not null default now()
);

create index idx_audit_owner   on public.audit_logs(owner_user_id);
create index idx_audit_entity  on public.audit_logs(entity_type, entity_id);

-- ----------------------------------------------------------------------------
-- user_settings
-- ----------------------------------------------------------------------------
-- Per-user app settings. One row per user.
create table public.user_settings (
  user_id                  uuid primary key references auth.users(id) on delete cascade,
  business_name            text default 'Lekka',
  default_currency         text default 'INR',
  default_bc_term_weeks    int  default 10,
  default_apr              numeric(6,3) default 24,
  default_language         text default 'en' check (default_language in ('en','te')),
  reminder_template_due    text default 'Hi {customerName}, this is a reminder that ₹{amount} is due today for your account. Please pay when possible. Thank you.',
  reminder_template_late   text default 'Hi {customerName}, this is a reminder that ₹{amount} was due on {dueDate}. Please update once paid. Thank you.',
  reminder_time_hhmm       text default '09:00',
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- Helpful view: installment with computed OVERDUE status
-- ----------------------------------------------------------------------------
-- We don't store 'OVERDUE' on installments — we compute it on read.
-- This view exposes effective_status which is what the UI should use.
create or replace view public.v_installments_with_effective_status as
select
  i.*,
  case
    when i.status in ('PAID','WAIVED') then i.status
    when i.due_date < current_date and i.status in ('PENDING','PARTIAL') then 'OVERDUE'
    when i.due_date = current_date and i.status in ('PENDING','PARTIAL') then 'DUE_TODAY'
    else i.status
  end as effective_status,
  (i.due_amount - i.paid_amount) as balance,
  a.account_type,
  a.customer_id,
  c.full_name as customer_name,
  c.phone_number as customer_phone
from public.installments i
join public.accounts  a on a.id = i.account_id
join public.customers c on c.id = a.customer_id;

comment on table public.customers       is 'People owing money to the lender. One row per person.';
comment on table public.accounts        is 'A single lending arrangement. BC_WEEKLY or MONTHLY_INTEREST.';
comment on table public.installments    is 'Scheduled repayments. Generated automatically on account create.';
comment on table public.payments        is 'Actual money received. Soft-deleted via voided flag.';
comment on table public.reminders       is 'Scheduled or sent reminder messages.';
comment on table public.audit_logs      is 'Append-only history of edits for compliance.';
comment on table public.user_settings   is 'Per-user app preferences and templates.';
